---
services:
  plugin:
    build: .
    ports:
      - 8080:8080
  
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:8.6.1-arm64
    depends_on:
      - plugin
    volumes:
      - type: bind
        source: ./logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: ./pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
      - type: bind
        source: ./sample.log
        target: /tmp/sample.log
        read_only: true